---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@v22

      - name: Format
        run: nix develop --command treefmt --fail-on-change

  build:
    name: Build docs site
    runs-on: ubuntu-latest
    needs: quality

    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@v22

      - name: Build
        run: nix develop --command mdbook build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: book/

  deploy:
    name: Publish site
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
